language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g npm
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
after_script:
  - CODECLIMATE_REPO_TOKEN="${CODECLIMATE_REPO_TOKEN}" codeclimate < bin/coverage/lcov/lcov.info
